version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  # mongodb:
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db
  #   restart: always
  #   networks:
  #     - internal-network

volumes:
  redis_data:
  # mongo_data:

networks:
  internal-network:
    driver: bridge